# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 13:18
from __future__ import unicode_literals

import chembl_core_db.db.customFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chembl_core_model', '0007_auto_20150806_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biotherapeuticcomponents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fracclassification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hracclassification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iracclassification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='moleculefracclassification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='moleculehracclassification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patentusecodes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productpatents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sitecomponents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='structuralalerts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='structuralalertsets',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='targetcomponents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='targetdictionary',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='targetrelations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='targettype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usanstems',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='celldictionary',
            name='downgraded',
            field=chembl_core_db.db.customFields.ChemblNullableBooleanField(default=False, help_text='Indicates the cell line has been removed (if set to 1)'),
        ),
        migrations.AlterField(
            model_name='chemblidlookup',
            name='entity_type',
            field=chembl_core_db.db.customFields.ChemblCharField(choices=[(b'ASSAY', b'ASSAY'), (b'CELL', b'CELL'), (b'COMPOUND', b'COMPOUND'), (b'DOCUMENT', b'DOCUMENT'), (b'TARGET', b'TARGET')], help_text='Type of entity (e.g., COMPOUND, ASSAY, TARGET)', max_length=50),
        ),
        migrations.AlterField(
            model_name='compoundproperties',
            name='acd_most_bpka',
            field=chembl_core_db.db.customFields.ChemblPositiveDecimalField(blank=True, decimal_places=2, help_text='The most basic pKa calculated using ACDlabs v12.01', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='defineddailydose',
            name='ddd_value',
            field=chembl_core_db.db.customFields.ChemblPositiveDecimalField(blank=True, decimal_places=2, help_text='Value of defined daily dose', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='drugmechanism',
            name='selectivity_comment',
            field=chembl_core_db.db.customFields.ChemblCharField(blank=True, choices=[(b'Broad spectrum', b'Broad spectrum'), (b'EDG5 less relevant', b'EDG5 less relevant'), (b'FGFR 1, 2 + 3', b'FGFR 1, 2 + 3'), (b'M3 selective', b'M3 selective'), (b"Non-selective but type 5 receptor is overexpressed in Cushing's disease", b"Non-selective but type 5 receptor is overexpressed in Cushing's disease"), (b'Selective', b'Selective'), (b'Selective for the brain omega-1 receptor (i.e. BZ1-type, i.e. alpha1/beta1/gamma2-GABA receptor)', b'Selective for the brain omega-1 receptor (i.e. BZ1-type, i.e. alpha1/beta1/gamma2-GABA receptor)'), (b'Selectivity for types 2, 3 and 5', b'Selectivity for types 2, 3 and 5'), (b'selectivity for beta-3 containing complexes', b'selectivity for beta-3 containing complexes')], help_text='Additional comments regarding the selectivity of the drug', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moleculedictionary',
            name='forced_reg_index',
            field=chembl_core_db.db.customFields.ChemblPositiveIntegerField(db_index=True, default=0, help_text='Number of times this structure key has been forced to be registered'),
        ),
        migrations.AlterField(
            model_name='moleculedictionary',
            name='public',
            field=chembl_core_db.db.customFields.ChemblBooleanField(default=False, help_text='Whether this molecule has been marked as public'),
        ),
        migrations.AlterField(
            model_name='moleculedictionary',
            name='structure_type',
            field=chembl_core_db.db.customFields.ChemblCharField(choices=[(b'NONE', b'NONE'), (b'MOL', b'MOL'), (b'SEQ', b'SEQ'), (b'BOTH', b'BOTH'), (b'BLIND_ID', b'Blind ID')], default=b'MOL', help_text='Indications whether the molecule has a small molecule structure or a protein sequence (MOL indicates an entry in the compound_structures table, SEQ indications an entry in the protein_therapeutics table, NONE indicates an entry in neither table, e.g., structure unknown)', max_length=10),
        ),
        migrations.AlterField(
            model_name='proteinclassification',
            name='downgraded',
            field=chembl_core_db.db.customFields.ChemblBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='targetcomponents',
            name='homologue',
            field=chembl_core_db.db.customFields.ChemblPositiveIntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2')], default=0, help_text='Indicates that the given component is a homologue of the correct component (e.g., from a different species) when set to 1. This may be the case if the sequence for the correct protein/nucleic acid cannot be found in sequence databases. A value of 2 indicates that the sequence given is a representative of a species group, e.g., an E. coli protein to represent the target of a broad-spectrum antibiotic.'),
        ),
        migrations.AlterField(
            model_name='targetcomponents',
            name='relationship',
            field=chembl_core_db.db.customFields.ChemblCharField(choices=[(b'COMPARATIVE PROTEIN', b'COMPARATIVE PROTEIN'), (b'EQUIVALENT PROTEIN', b'EQUIVALENT PROTEIN'), (b'FUSION PROTEIN', b'FUSION PROTEIN'), (b'GROUP MEMBER', b'GROUP MEMBER'), (b'INTERACTING PROTEIN', b'INTERACTING PROTEIN'), (b'PROTEIN SUBUNIT', b'PROTEIN SUBUNIT'), (b'RNA', b'RNA'), (b'RNA SUBUNIT', b'RNA SUBUNIT'), (b'SINGLE PROTEIN', b'SINGLE PROTEIN'), (b'UNCURATED', b'UNCURATED'), (b'SUBUNIT', b'SUBUNIT')], default='UNCURATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='targetdictionary',
            name='downgraded',
            field=chembl_core_db.db.customFields.ChemblBooleanField(default=False, help_text='Flag to indicate that the target is downgraded (if equal to 1)'),
        ),
        migrations.AlterField(
            model_name='targetdictionary',
            name='species_group_flag',
            field=chembl_core_db.db.customFields.ChemblBooleanField(default=False, help_text="Flag to indicate whether the target represents a group of species, rather than an individual species (e.g., 'Bacterial DHFR'). Where set to 1, indicates that any associated target components will be a representative, rather than a comprehensive set."),
        ),
    ]
