# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembl_core_model', '0008_auto_20161128_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindingsites',
            name='domains',
            field=models.ManyToManyField(blank=True, through='chembl_core_model.SiteComponents', to='chembl_core_model.Domains'),
        ),
        migrations.AlterField(
            model_name='biotherapeutics',
            name='bio_component_sequences',
            field=models.ManyToManyField(blank=True, through='chembl_core_model.BiotherapeuticComponents', to='chembl_core_model.BioComponentSequences'),
        ),
        migrations.AlterField(
            model_name='compoundrecords',
            name='assays',
            field=models.ManyToManyField(blank=True, through='chembl_core_model.Activities', to='chembl_core_model.Assays'),
        ),
        migrations.AlterField(
            model_name='compoundrecords',
            name='products',
            field=models.ManyToManyField(blank=True, through='chembl_core_model.Formulations', to='chembl_core_model.Products'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='component_sequences',
            field=models.ManyToManyField(blank=True, through='chembl_core_model.ComponentDomains', to='chembl_core_model.ComponentSequences'),
        ),
        migrations.AlterField(
            model_name='moleculedictionary',
            name='assays',
            field=models.ManyToManyField(blank=True, through='chembl_core_model.Activities', to='chembl_core_model.Assays'),
        ),
        migrations.AlterField(
            model_name='moleculedictionary',
            name='docs',
            field=models.ManyToManyField(blank=True, through='chembl_core_model.CompoundRecords', to='chembl_core_model.Docs'),
        ),
        migrations.AlterField(
            model_name='moleculedictionary',
            name='products',
            field=models.ManyToManyField(blank=True, through='chembl_core_model.Formulations', to='chembl_core_model.Products'),
        ),
        migrations.AlterField(
            model_name='proteinclassification',
            name='component_sequences',
            field=models.ManyToManyField(blank=True, through='chembl_core_model.ComponentClass', to='chembl_core_model.ComponentSequences'),
        ),
    ]
