# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chembl_business_model', '0001_initial'),
        ('cbh_chembl_model_extension', '0001_initial'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='cbhcompoundbatch',
#            name='related_molregno',
#            field=models.ForeignKey(blank=True, default=None, help_text=b'The foreign key relationship to the MoleculeDictionary record generated for this compound. May be null for compounds without a structure or inventory items', null=True, on_delete=django.db.models.deletion.CASCADE, to='chembl_business_model.MoleculeDictionary'),
#        ),
    ]
