# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_chembl_model_extension', '0038_auto_20160603_0932'),
        ('cbh_chembl_model_extension', '0002_cbhcompoundbatch_related_molregno'),
    ]

    operations = [
    ]
