# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 07:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_core_model', '0056_auto_20161124_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinningconfig',
            name='maintenance_warning_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 24, 7, 57, 7, 692834, tzinfo=utc), help_text=b'The end time of the maintenance warning message'),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='maintenance_warning_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 24, 7, 57, 7, 692783, tzinfo=utc), help_text=b'The start time of the maintenance warning message'),
        ),
    ]
