# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_core_model', '0057_auto_20161124_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinningconfig',
            name='login_page_subtitle',
            field=models.CharField(default=b'Home of SGC Compound Registration', help_text=b'Text to use as the login page subtitle', max_length=300),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='login_page_title',
            field=models.CharField(default=b'Welcome to SGC Global ChemiReg', help_text=b'Text to use as the login page title', max_length=300),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='maintenance_warning_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 24, 7, 58, 49, 973192, tzinfo=utc), help_text=b'The end time of the maintenance warning message'),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='maintenance_warning_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 24, 7, 58, 49, 973163, tzinfo=utc), help_text=b'The start time of the maintenance warning message'),
        ),
    ]
