# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cbh_core_model', '0059_auto_20161128_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinningconfig',
            name='maintenance_warning_end',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text=b'The end time of the maintenance warning message'),
        ),
        migrations.AlterField(
            model_name='skinningconfig',
            name='maintenance_warning_start',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text=b'The start time of the maintenance warning message'),
        ),
    ]
